### ISSUE TITLE
Probot Kubernetes getNamespace Function failing outside cluster

### ISSUE THREAD

**Issue by djach7** [operate-first/probot-extensions#43]
**Describe the bug**
When operating bot outside of cluster we're having trouble accessing the correct namespace. getNamespace seems to be returning the context namespace rather than the current namespace. We tried replacing this line with `kc.getCurrentContextObject().namespace`, but this method is private and typescript wasn't pleased. The specific line causing us issues is below:

https://github.com/operate-first/probot-extensions/blob/533c9cf245adfb482784fc0adaec9daee3d9542d/packages/probot-kubernetes/index.ts#L25

**To Reproduce**
1. `kubectl config set-context --current --namespace copilot-ops-bot`
2. `npm run dev`
3. Installed bot on target repo
4. `getNamespace` returns kind-kind

**Expected behavior**
We want to be able to run the bot outside the cluster and specify a namespace. 

@tumido @guymguym

**Comment by tumido** [comment]
Can you try setting the namespace via `oc project <namespace>`. I don't know if it's using different means to set/export the namespace to local kube context, but it always worked for me...

**Comment by tumido** [comment]
Resolved via: #46
